language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install ."
# command to run tests
script:
  - "pytest -v tests/authorization_test.py"
  - "pytest -v tests/online_test.py"
